import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer/Footer";
import { Providers } from "./providers";
import { notojp } from "@/utiles/font";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja-JP" className={`${notojp.variable}`}>
      <Head>
        <title>犬の幼稚園、犬の訓練、犬のしつけ | 浪賀警察犬学校</title>
        <link rel="icon" href="/home_icon1.png" />
        <meta name="description" content="犬の幼稚園、犬の訓練、訪問訓練、出張訓練など経験豊富な訓練士がワンちゃんのしつけをサポートします。" />
        <meta name="keywords" content="犬の幼稚園, 犬の訓練, 犬のしつけ, 大阪, 大阪犬の訓練所, ドッグラン" />
        <meta property="og:title" content="犬の幼稚園、犬の訓練、犬のしつけ | 浪賀警察犬学校" />
        <meta property="og:description" content="犬の幼稚園、犬の訓練、訪問訓練、出張訓練など経験豊富な訓練士がワンちゃんのしつけをサポートします。" />
        <meta property="og:url" content="https://rogadogschool.com/" />
      </Head>
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
